name: HowAboutQuestion Ddoby

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Let's move, Ddoby!
        uses: actions/checkout@v4

      - name: Inspect it, Ddoby!
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build it, Ddoby!
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Wake Up Ddoby!
        run: |
          sudo systemctl restart howaboutquestion
